/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_borodust_alienworks_android_AlienWorksNative */

#ifndef _Included_org_borodust_alienworks_android_AlienWorksNative
#define _Included_org_borodust_alienworks_android_AlienWorksNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_borodust_alienworks_android_AlienWorksNative
 * Method:    loadLibrariesGlobally
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_borodust_alienworks_android_AlienWorksNative_init(JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
